### ISSUE TITLE
AbstractTestCase, Requirement vs NormativeStatement

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/AutomatedDocumentation#12]
In the current diagram, an AbstractTestCase is only associated with Requirements.

Does that mean Recommendations and Permissions cannot have a Test Case?

**Comment by jetgeo** [comment]
I believe so, we have discussed this earlier. See https://github.com/orgs/ISO-TC211/teams/adhoc-automated-documentation/discussions/11?from_comment=7#discussion-11-comment-7

I don't suppose recommendations should be tested for conformance? But perhaps permissions should?
