### ISSUE TITLE
Consistency with depending on an ExternalSpecification

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/AutomatedDocumentation#13]
In the current diagram, the RequirementsClass can depend on an ExternalSpecification.

If we consider that an ExternalSpecification is an ISO/TC 211 specification, it could also be a ModularSpecification.

However, a ModularSpecification contains RequirementSuites (also note the pluralisation consistency with RequirementsClass here). The current arrangement means that a RequirementsClass technically could depend on a RequirementSuite, which violates the current diagram.

**Comment by jetgeo** [comment]
Same as https://github.com/ISO-TC211/AutomatedDocumentation/issues/11. I believe this is meant to be a simple reference, @heidivanparys ?

**Comment by jetgeo** [comment]
Closing this issue, suggest further discussions in an NWIP for Modular Specs.
