### ISSUE TITLE
Where does NormativeStatement actually carry content?

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/AutomatedDocumentation#14]
The current NormativeStatement allows containing `text` (inherited from IdentifiedObject), is that where it carries the statement itself?

When a NormativeStatement contains subStatements, what does this mean?

If the `text` is empty, we assume that NormativeStatement "consists" of its subStatements. In this case a subStatement is a "requirement part".

If the `text` is non-empty, there are two interpretations that need to be clarified:
1. A NormativeStatement "consists" its subStatements but the `text` is a description of the statement.
2. Its subStatements are hierarchically required, where the current `text` attribute of the NormativeStatement actually provides instruction to execute the subStatements. e.g. "If A, then the subStatements are required".

**Comment by jetgeo** [comment]
The text is meant for the statement itself, yes. 

I have no practical example of a hierarchy of statements, actually, I don't remember when av why this option was added...

TBD.

**Comment by jetgeo** [comment]
Closing this issue, suggest further discussions in an NWIP for Modular Specs.
