### ISSUE TITLE
Stereotype needed for "external specifications"

### ISSUE THREAD

**Issue by heidivanparys** [ISO-TC211/AutomatedDocumentation#5]
A stereotype would be needed for external specifications, so that the dependencies can be modelled properly.

![image](https://user-images.githubusercontent.com/11427611/133083132-1de00f2f-b571-4851-9250-3903e6f85931.png)

With "external specification" I mean a specification that is neither a ISO/TC 211 nor an OGC standard. An example: requirements class "UML 2" in [ISO 19103](https://www.iso.org/obp/ui#iso:std:iso:19103:ed-1:v1:en) has a dependency on [ISO/IEC 19505-2:2012](https://www.iso.org/obp/ui#iso:std:iso-iec:19505:-2:ed-1:v1:en).

![image](https://user-images.githubusercontent.com/11427611/133084252-d4bc9a02-227e-4069-997a-1e3abc63dedd.png)

If all standards were modelled like that, you could run queries such as "Which of our standards have a dependency on ISO/IEC 19505-2:2012?"

Note: I don't know whether "external specification" is the best term, but it is what I could come up with so far.

**Comment by jetgeo** [comment]
Agree. I think "ExternalSpecification" is a meaningful name.

**Comment by dr-shorthair** [comment]
UML has a basic assumption of working in a closed system. 
Identifiers for classifiers are not expected to be used externally. 
This is a real tension for distributed systems, and web identifiers.

**Comment by PeterParslow** [comment]
Simon, that's an interesting assertion. I would agree that many people who use UML have those assumptions, and design without reuse - so identifiers are not easily used externally.

But is it really an assumption of UML itself?

**Comment by jetgeo** [comment]
@dr-shorthair UML models are closed systems - true. But that's not an argument for not describing external relations in a UML model. External identifiers can easily be described in UML models and used in implementations that are more open. Let's rather discuss how we can do that.

**Comment by jetgeo** [comment]
Updated in the conceptual model.
See https://github.com/ISO-TC211/AutomatedDocumentation/wiki/Conceptual-model-of-normative-statements-and-conformance
