### ISSUE TITLE
Specification target

### ISSUE THREAD

**Issue by heidivanparys** [ISO-TC211/AutomatedDocumentation#6]
It should be possible to indicate the specification target of a requirements class in the model.

**Comment by heidivanparys** [comment]
One option is the use of a tagged value, see image below, but another option could be to change the profile and actually create an association to indicate the specification target, see also #7.

![image](https://user-images.githubusercontent.com/11427611/133113913-ced6db80-de77-4e08-9898-448ff02ef716.png)

**Comment by jetgeo** [comment]
We have standardizationTarget for ConformanceClass. What would be the difference between a RequirementsClass.specificationTarget and a ConformanceClass.standardizationTarget?

**Comment by heidivanparys** [comment]
> We have standardizationTarget for ConformanceClass.

standardizationTarget is not present in https://github.com/ISO-TC211/AutomatedDocumentation/blob/master/Conceptual%20model/ConformanceAndTestingProfile.xml which is probably why I didn't take that into account while writing this issue, but it is indeed on the image here: https://github.com/ISO-TC211/AutomatedDocumentation/blob/master/Conceptual%20model/Modified%20conceptual%20model%20with%20normative%20statements.png

> What would be the difference between a RequirementsClass.specificationTarget and a ConformanceClass.standardizationTarget?

In the 19105 project it was decided to use the term "specification target", as this standard can be used for all kinds of specifications, not only specifications that reach "standard" status.

Then the question is, what comes first. When creating a specification, the process seems to be:

1. Drafting the requirements and organise them into requirements classes
2. Drafting the tests and the conformance classes once the requirements and requirements classes are relatively stable (see e.g. the note on https://docs.ogc.org/DRAFTS/19-079r1.html#ats).

So I would argue that it is the requirements class that should hold the information on the specification target, to allow for actually modelling it in the early phases of drafting a specification – without having to model the conformance classes already in those phases.

And note also the definition of specification target, it contains "requirements", not e.g. "test".

**3.23**
**specification target**
entity to which some requirements of a specification apply

**Comment by jetgeo** [comment]
Thanks, @heidivanparys. I see that I need to update GitHub with the latest changes of the model and profile :).

**Comment by jetgeo** [comment]
Committed the updated profile: https://github.com/ISO-TC211/AutomatedDocumentation/commit/2638b5a1f95b2a8b0340bc00c0f2f28047e7e1fc

**Comment by jetgeo** [comment]
Updated in the conceptual model. 
See https://github.com/ISO-TC211/AutomatedDocumentation/wiki/Conceptual-model-of-normative-statements-and-conformance

**Comment by jetgeo** [comment]
Uploaded a new conceptual model, updated with Specification Target as class (https://github.com/ISO-TC211/AutomatedDocumentation/commit/3e4733d878ff4dab48f5aba08a880f21b53605c2).
See also #7
