### ISSUE TITLE
Package vs. Class as metaclass

### ISSUE THREAD

**Issue by heidivanparys** [ISO-TC211/AutomatedDocumentation#7]
I am wondering whether it would be smarter to use `Class` as the metaclass for `RequirementsClass`, `ModularSpecification`, etc. instead of `Package`?

It would give the advantage that associations can be created from e.g. a requirements class to something else, e.g. to indicate the specification target of a requirements class. Which then again could make it possible to ask questions like "Which requirements classes standardize application schemas?"? Creating an association is not possible for packages it seems.

![image](https://user-images.githubusercontent.com/11427611/133112164-f4c8304a-a57f-453c-97c8-5998da77e612.png)

![image](https://user-images.githubusercontent.com/11427611/133112293-f5aae582-9038-45e5-8e74-f178d03d6d70.png)

Nesting classes is UML compliant as far as I can see, so no problem there.

![image](https://user-images.githubusercontent.com/11427611/133112566-847fcf4d-822e-4df1-b26b-dd6d75766d5d.png)

![image](https://user-images.githubusercontent.com/11427611/133112864-90c23b44-8f4a-43d7-9f20-ca486b3e5dff.png)

> A Class acts as the namespace for various kinds of Classifiers defined within its scope, including Classes. Nested
> Classifiers are members of the namespace of the containing Class.

**Comment by jetgeo** [comment]
This seems reasonable. But do we need to nest the classes? We could use aggregations as well. I guess nesting is better for visualization.

**Comment by heidivanparys** [comment]
Aggregation could be used as well (but nesting is also expressing aggregations, see in previous comment). I don't have a strong opinion. For discussion in the group, I would say.

**Comment by jetgeo** [comment]
@heidivanparys : In the figure above, you have added a stereotype for SpecificationTarget as well. While in https://github.com/ISO-TC211/AutomatedDocumentation/issues/6, we are talking about specificationTarget as an attribute. Do you think the specification target should be a class? If so, why?

**Comment by jetgeo** [comment]
I have uploaded a new profile with all concepts as class extensions (https://github.com/ISO-TC211/AutomatedDocumentation/commit/72091c74d7483c4669fa50023691db0a377c9489). Let's try and see how it works.

**Comment by jetgeo** [comment]
Uploaded a new conceptual model, updated with Specification Target as class (https://github.com/ISO-TC211/AutomatedDocumentation/commit/3e4733d878ff4dab48f5aba08a880f21b53605c2).
See also #6 .
